Repository mohamedelziat50/Aloura-MIU, pull requests merged in 2025-05, with the labels that each got.

#267 Account Page✅
  public/css/account.css
  public/js/account.js
  routes/frontend.js
  views/account.ejs
  views/all-fragrances.ejs
Labels: Review effort 2/5

#278 more cleaner code
  public/js/admin.js
  views/admin/admin.ejs
Labels: Review effort 2/5

#280 Seif
  public/css/fragrance-quiz.css
  public/js/quiz.js
  views/fragrance-quiz.ejs
Labels: Review effort 2/5

#287 Included partials & dark mode in the work for collections & gifting
  public/css/collections-dimension.css
  public/css/gifting.css
  public/js/dark-mode.js
  views/collections.ejs
  views/gifting.ejs
  views/index.ejs
  views/partials/footer.ejs
Labels: Review effort 2/5

#297 GitHub Actions workflow to make sure you have the commits on master to merge the PR
  .github/workflows/simple-test.yml
Labels: Review effort 1/5

#300 some navbar adjustments in the quiz
  public/css/navBar.css
Labels: Review effort 1/5

#303 forgot to delelted the addUser file
  views/admin/addUser.ejs
Labels: Review effort 1/5

#304 fixed an error
  index.js
  public/css/addUser.css
  public/css/admin.css
  views/admin/admin.ejs
Labels: Review effort 1/5

#305 modified the auth rout
  controllers/auth.js
  index.js
  public/js/admin.js
  public/js/modal.js
  routes/auth.js
  views/account.ejs
  views/partials/navbar.ejs
Labels: Review effort 2/5

#306 fixed the login
  public/js/modal.js
Labels: Review effort 1/5

#307 fixed the credit card validation
  public/js/checkout.js
  views/checkout.ejs
Labels: Review effort 2/5

#309 made js with simpler logic
  public/js/fragrances-page.js
  views/fragrances-page.ejs
Labels: Review effort 2/5

#310 fully adjusted the select only 1 bar below titles
  public/css/fragrance-quiz.css
  public/js/quiz.js
  views/fragrance-quiz.ejs
Labels: Review effort 2/5

#312 Nabil
  controllers/frontend.js
  index.js
  public/css/all-fragrances.css
  public/css/fragrances-page.css
  routes/fragrance.js
  routes/frontend.js
  views/all-fragrances.ejs
  views/fragrances-page.ejs
Labels: Review effort 3/5

#313 the recommendation section with the email is done
  public/css/fragrance-quiz.css
  public/img/quizFinalRec.png
  views/fragrance-quiz.ejs
Labels: Review effort 2/5

#314 few modifications to the recommendation section in the fragrance quiz.
  views/fragrance-quiz.ejs
Labels: Review effort 1/5

#319 found a bug in the edit and fixed it
  controllers/users.js
  public/js/account.js
  views/account.ejs
Labels: Review effort 2/5

#321 the quiz is fully done and fully functional
  public/css/fragrance-quiz.css
  public/css/quizRec.css
  public/js/quiz.js
  views/fragrance-quiz.ejs
Labels: Review effort 3/5

#323 fixed the dropdown menu bug in all fragrance page and added more pric…
  views/admin/addFragrance.ejs
  views/admin/editFragrance.ejs
  views/all-fragrances.ejs
Labels: Review effort 2/5

#326 packages update
  package-lock.json
  package.json
Labels: Review effort 1/5

#328 added env example + some fluid changes
  .env
  .env.example
  public/js/script.js
Labels: Review effort 2/5

#329 some chatbot tazbitat
  controllers/chatbot.js
  public/js/chatbot.js
  views/all-fragrances.ejs
Labels: Review effort 2/5

#331 now you can send html in the email
  public/js/checkout.js
  utilities/emailService.js
Labels: Review effort 2/5

#333 added html base for the email just edit it and it will be sent
  controllers/auth.js
Labels: Review effort 2/5

#334 Nabil
  controllers/auth.js
  utilities/emailtemplates.js
Labels: Review effort 2/5

#335 .env.example addition + ran npm update
  .env.example
  package-lock.json
Labels: Review effort 1/5

#337 now when you press on add to cart the item is added to the array to t…
  controllers/auth.js
  controllers/users.js
  models/user.js
  public/js/all-fragrances.js
  routes/users.js
  utilities/smsService.js
  views/all-fragrances.ejs
Labels: Review effort 3/5
