Repository mohamedelziat50/Aloura-MIU, pull requests merged in 2025-06, with the labels that each got.

#347 fixed some imorts so we do not use anything from the .env directly we…
  controllers/auth.js
  middleware/auth.js
  routes/frontend.js
  views/checkout.ejs
Labels: Review effort 2/5

#348 Nabil
  controllers/auth.js
  package-lock.json
  package.json
Labels: Review effort 1/5

#354 Fragrance & User Delete Confirmation
  public/js/admin.js
  views/admin/admin.ejs
Labels: Review effort 2/5

#355 Checkout Backend, still will work on it's admin page
  controllers/frontend.js
  controllers/order.js
  models/order.js
  public/css/checkout.css
  public/js/cart.js
  public/js/checkout.js
  routes/order.js
  views/checkout.ejs
Labels: Review effort 3/5

#356 fixed some bugs
  controllers/fragrance.js
  public/css/gifting.css
  public/css/modal.css
  views/account.ejs
  views/admin/editUser.ejs
  views/partials/modal.ejs
Labels: Review effort 2/5

#360 Admin's Delete Order + Locked user/fragrance deletion if part of an order
  controllers/fragrance.js
  controllers/order.js
  controllers/users.js
  public/js/admin.js
  routes/order.js
  views/admin/admin.ejs
  views/partials/navbar.ejs
Labels: Review effort 2/5

#362 added payment info section inside view order page
  views/admin/viewOrder.ejs
Labels: Review effort 2/5

#367 fixed the proifle picture in the orderviewpage
  views/admin/viewOrder.ejs
Labels: Review effort 1/5

#369 subscribed users get send in an array with the admin page called subs…
  controllers/frontend.js
Labels: Review effort 2/5

#371 User's Order History Backend Done
  .env.example
  controllers/frontend.js
  public/css/user-orders.css
  public/js/user-orders.js
  routes/frontend.js
  views/account.ejs
  views/admin/admin.ejs
  views/admin/viewOrder.ejs
  views/user-orders.ejs
Labels: Review effort 3/5

#372 slight bug fixed
  views/admin/admin.ejs
Labels: Review effort 1/5

#375 Order stock - only when create order (next up is order status)
  controllers/fragrance.js
  controllers/frontend.js
  controllers/order.js
  views/all-fragrances.ejs
  views/fragrances-page.ejs
Labels: Review effort 3/5

#377 For Him/Her transition z-index fix
  public/css/style.css
  public/js/script.js
Labels: Review effort 2/5

#380 Order status - continued
  controllers/order.js
  public/css/user-orders.css
  views/admin/admin.ejs
  views/user-orders.ejs
Labels: Review effort 2/5

#382 Nabil
  public/js/admin.js
Labels: Review effort 2/5

#384 Adjusted the Cancel button aesthetically
  views/admin/admin.ejs
Labels: Review effort 1/5

#392 Rewind Button Added
  public/css/style.css
  public/js/script.js
  views/index.ejs
Labels: Review effort 2/5

#393 the cart is now populated with the gifts with no errors
  public/js/all-fragrances.js
  public/js/cart.js
  public/js/fragrances-page.js
  public/js/gifting.js
  routes/frontend.js
  views/partials/cart.ejs
Labels: Review effort 3/5

#395 Antoni
  public/css/admin.css
Labels: Review effort 1/5

#397 now the sign in with google works
  config/passport.js
  controllers/auth.js
  index.js
  models/user.js
  package-lock.json
  package.json
  public/js/modal.js
  routes/auth.js
  views/account.ejs
Labels: Review effort 3/5

#398 fixed an import
  config/passport.js
Labels: Review effort 1/5

#399 fixing bug
  index.js
Labels: Review effort 1/5

#400 woriking in the bug
  config/passport.js
Labels: Review effort 1/5

#401 Nabil
  config/passport.js
  controllers/auth.js
  index.js
  public/js/admin.js
  routes/auth.js
  views/admin/admin.ejs
Labels: Review effort 2/5

#403 now if the card is not supported no error page it just shows not supp…
  views/admin/viewOrder.ejs
Labels: Review effort 2/5

#415 jsut to make the google work hopefuly
  config/passport.js
  config/secrets.js
  controllers/auth.js
Labels: Review effort 2/5

#418 fixed rendering reviews
  controllers/frontend.js
Labels: Review effort 1/5

#419 now the approved fragrances are added to the landing page slider successfully.
  controllers/fragrance.js
  controllers/frontend.js
  models/fragrance.js
  package-lock.json
  public/css/admin.css
  public/js/admin.js
  views/admin/admin.ejs
  views/index.ejs
Labels: Review effort 3/5

#420 Nabil
  utilities/emailtemplates.js
Labels: Review effort 1/5

#421 Admin dashboard analytics + review page all dynamically loaded done
  controllers/frontend.js
  public/css/admin.css
  routes/frontend.js
  views/admin/addFragrance.ejs
  views/admin/admin.ejs
  views/admin/editFragrance.ejs
  views/user-orders.ejs
  views/user-reviews.ejs
Labels: Review effort 2/5

#422 Ramyclean merged
  controllers/users.js
  public/css/gifting.css
  public/js/all-fragrances.js
  public/js/gifting.js
  views/admin/addFragrance.ejs
  views/admin/editFragrance.ejs
  views/admin/viewOrder.ejs
  views/checkout.ejs
  views/partials/cart.ejs
  views/user-orders.ejs
Labels: Review effort 3/5

#423 An order item can only be reviewed ONCE. + fixed a bug inside admin
  controllers/frontend.js
  controllers/review.js
  models/order.js
  public/js/user-reviews.js
  views/admin/admin.ejs
  views/user-orders.ejs
  views/user-reviews.ejs
Labels: Review effort 2/5

#424 Reviewed Item Validation
  controllers/review.js
  public/css/user-orders.css
  views/user-orders.ejs
Labels: Review effort 2/5

#426 the remove card was non sense, it make sense now
  controllers/users.js
  public/js/all-fragrances.js
  public/js/cart.js
  public/js/fragrances-page.js
  public/js/gifting.js
  views/partials/cart.ejs
Labels: Review effort 2/5

#428 footer changes, check it out bc we are unsure if we are gonna use it …
  public/css/footer.css
  views/collections.ejs
  views/partials/footer.ejs
Labels: Review effort 3/5

#427 frontend in the view order is better now and if there is no gift in t…
  controllers/chatbot.js
  controllers/fragrance.js
  controllers/frontend.js
  controllers/gifting.js
  controllers/order.js
  controllers/review.js
  controllers/users.js
  middleware/auth.js
  middleware/multer.js
  models/fragrance.js
  models/order.js
  models/review.js
  models/user.js
  public/js/3dmodel.js
  public/js/admin.js
  public/js/all-fragrances.js
  public/js/back-to-top.js
  public/js/cart.js
  public/js/checkout.js
  public/js/collections-dimension.js
  public/js/dark-mode.js
  public/js/fragrances-page.js
  public/js/gifting.js
  public/js/our-story.js
  public/js/page-loader.js
  public/js/quiz.js
  public/js/script.js
  public/js/scrolly.js
  public/js/user-orders.js
  public/js/user-reviews.js
  routes/order.js
  routes/review.js
  routes/users.js
  views/admin/addFragrance.ejs
  views/admin/editFragrance.ejs
  views/admin/viewOrder.ejs
Labels: Review effort 2/5

#430 nav bar changes, slightly better behavior
  public/css/navBar.css
Labels: Review effort 2/5

#431 some controller getIndex changes
  controllers/frontend.js
  models/fragrance.js
Labels: Review effort 2/5

#432 a little modifications in the gifting page front end + orders sectio…
  views/admin/admin.ejs
  views/gifting.ejs
Labels: Review effort 1/5

#433 very slight fix for images display in all-fragrances
  public/css/all-fragrances.css
Labels: Review effort 1/5

#434 increase the limit on the post request
  index.js
Labels: Review effort 1/5

#435 Ramyclean merged
  index.js
Labels: Review effort 1/5

#436 dark-mode for forgotten pages done + small toastie change in addToLandingSlider in admin
  public/js/admin.js
  public/js/dark-mode.js
  views/account.ejs
  views/user-orders.ejs
  views/user-reviews.ejs
Labels: Review effort 2/5

#440 quiz is now working perfectly fine.
  controllers/fragrance.js
  index.js
  public/css/style.css
  public/js/quiz.js
  routes/quiz.js
Labels: Review effort 3/5

#460 Shop All/ Buy as a Gift button in index + updated .env.example & package-lock.json
  .env.example
  package-lock.json
  views/index.ejs
Labels: Review effort 2/5

#463 user cart error msg fix + removed unneccesary console logs
  controllers/frontend.js
  public/js/all-fragrances.js
  public/js/fragrances-page.js
Labels: Review effort 2/5

#467 Update admin.ejs
  views/admin/admin.ejs
Labels: Review effort 1/5

#470 fixed the add to user button on smaller screens
  public/css/admin.css
Labels: Review effort 2/5

#472 supposed will fix the blue icons problem in the nav bar
  public/css/navBar.css
Labels: Review effort 1/5

#473 reduced the padding in the smaller screens for the border of shopping…
  public/css/navBar.css
Labels: Review effort 1/5

#474 Explore Fragrances Cleaner, Stock Restoration, Admin Dashboard Enhanced, Redirects after succesful operations (for better experience), and removed some nuisance console logs
  controllers/order.js
  controllers/review.js
  public/css/style.css
  public/js/checkout.js
  public/js/user-orders.js
  public/js/user-reviews.js
  views/admin/admin.ejs
  views/index.ejs
Labels: Review effort 3/5

#475 Consistent EGP Currency + Out-of-stock bug handled/front end addition + Fixed edit fragrance bug
  public/js/admin.js
  public/js/all-fragrances.js
  public/js/fragrances-page.js
  public/js/script.js
  public/js/user-orders.js
  views/admin/admin.ejs
  views/admin/editFragrance.ejs
  views/admin/viewOrder.ejs
  views/checkout.ejs
  views/index.ejs
  views/user-orders.ejs
Labels: Review effort 2/5

#477 SEO & Favicons
  views/404.ejs
  views/account.ejs
  views/admin/addFragrance.ejs
  views/admin/admin.ejs
  views/admin/editFragrance.ejs
  views/admin/editUser.ejs
  views/admin/viewOrder.ejs
  views/all-fragrances.ejs
  views/checkout.ejs
  views/collections.ejs
  views/fragrance-quiz.ejs
  views/fragrances-page.ejs
  views/gifting.ejs
  views/index.ejs
  views/nightlife-collection.ejs
  views/our-story.ejs
  views/user-orders.ejs
  views/user-reviews.ejs
Labels: Review effort 2/5, Possible security concern

#478 absolute URLs for assets(images, css, js) and links(hrefs) across all views
  views/account.ejs
  views/all-fragrances.ejs
  views/checkout.ejs
  views/collections.ejs
  views/fragrance-quiz.ejs
  views/gifting.ejs
  views/index.ejs
  views/our-story.ejs
  views/partials/footer.ejs
  views/partials/modal.ejs
  views/partials/navbar.ejs
Labels: Review effort 2/5

#481 removed all the chatbot js and css inclueds and left it only in the c…
  views/account.ejs
  views/fragrances-page.ejs
  views/user-orders.ejs
  views/user-reviews.ejs
Labels: Review effort 1/5

#483 Nabil
  public/css/style.css
Labels: Review effort 1/5

#485 Last issue fixes <3
  controllers/frontend.js
  public/css/admin.css
  public/js/gifting.js
  views/gifting.ejs
Labels: Review effort 2/5
