Repository mohamedelziat50/Aloura-MIU, pull requests merged in 2025-04, with the labels that each got.

#183 few changes to the quiz
  public/css/fragrance-quiz.css
Labels: Review effort 2/5

#185 quiz updates, started a new section how strong do you like your perfume
  public/css/fragrance-quiz.css
  views/fragrance-quiz.ejs
Labels: Review effort 2/5

#186 Seif
  public/css/fragrance-quiz.css
  views/fragrance-quiz.ejs
Labels: Review effort 2/5

#188 Added 'Gifting' li & Removed search bar icon from navbar
  public/css/navBar.css
  views/partials/navbar.ejs
Labels: Review effort 1/5

#192 Hover effects + Carousel animations + Images Equalized
  public/css/style.css
  public/js/script.js
  views/index.ejs
Labels: Review effort 3/5

#197 Fluid Properties&Color✅
  public/css/ourStory.css
  public/css/style.css
  public/js/fluidEffect.js
  public/js/fluidEffect/app.js
  public/js/fluidEffect/backup-fluid.min.js
  public/js/fluidEffect/female-app.js
  public/js/fluidEffect/fluid.min.js
  public/js/fluidEffect/male-app.js
  public/js/script.js
  views/index.ejs
Labels: Review effort 2/5

#211 Nabil
  public/css/navBar.css
  routes/allroutes.js
  views/partials/navbar.ejs
Labels: Review effort 2/5

#213 Dark Mode - Majorly Done, Minor Still
  public/css/fragrances-page.css
  public/css/style.css
  public/img/spicebomb1.jpg
  public/img/spicebomb2.jpg
  public/js/dark-mode.js
  views/index.ejs
Labels: Review effort 2/5

#214 Working on bug fixes (issues related)
  public/css/cart.css
  public/css/modal.css
  public/css/style.css
  public/js/modal.js
  public/js/our-story.js
  views/our-story.ejs
Labels: Review effort 2/5

#215 Fluid Mostly Done, Except Specs Problem
  public/css/ourStory.css
  public/css/style.css
  public/js/fluidEffect/app.js
  public/js/fluidEffect/female-app.js
  public/js/fluidEffect/male-app.js
  public/js/our-story.js
  public/js/script.js
Labels: Review effort 2/5

#216 Modal&Cart Responsiveness✅
  public/css/cart.css
  public/css/modal.css
Labels: Review effort 2/5

#217 Minor fluid changes
  public/js/fluidEffect/female-app.js
  public/js/fluidEffect/male-app.js
Labels: Review effort 1/5

#219 Refactor authentication and user handling in routes and views
  controllers/auth.js
  index.js
  models/user.js
  public/js/modal.js
  routes/allroutes.js
  views/admin.ejs
  views/partials/navbar.ejs
Labels: Review effort 3/5

#222 Adjusted incorrect memory reading + OR instead of AND (GPU Or high cores/ram)
  public/js/fluidEffect/app.js
  public/js/fluidEffect/female-app.js
  public/js/fluidEffect/male-app.js
Labels: Review effort 2/5

#223 nvm that OR broke everything💀
  public/js/fluidEffect/app.js
  public/js/fluidEffect/female-app.js
  public/js/fluidEffect/male-app.js
Labels: Review effort 1/5

#225 Font for main section index.ejs + console fluid msg
  public/css/style.css
  public/js/fluidEffect/app.js
  public/js/fluidEffect/female-app.js
  public/js/fluidEffect/male-app.js
  views/index.ejs
Labels: Review effort 2/5

#226 Fix ourstory layout shifts when video changes & mobile sound not working (will test there.)
  public/css/ourStory.css
  public/js/our-story.js
Labels: Review effort 2/5

#227 Hopefully this fixes sound/video on mobile
  public/js/our-story.js
  views/our-story.ejs
Labels: Review effort 3/5

#228 Create dependabot.yml - To update dependencies
  .github/dependabot.yml
Labels: Review effort 1/5

#234 finished the last section of the fragrance quiz
  public/css/fragrance-quiz.css
Labels: Review effort 1/5

#235 font changes to the quiz.
  public/css/fragrance-quiz.css
  public/js/quiz.js
  views/fragrance-quiz.ejs
Labels: Review effort 2/5

#236 background color changes aashan hisham
  public/css/fragrance-quiz.css
Labels: Review effort 2/5

#238 little modifications in the fragrances-page and it became responsive
  public/css/fragrances-page.css
  public/img/best-quality.webp
  public/img/delivery.webp
  views/fragrances-page.ejs
Labels: Review effort 2/5

#240 Nabil
  .env
  .gitignore
  config/db.js
  config/secrets.js
  controllers/auth.js
  controllers/fragrance.js
  controllers/order.js
  controllers/publicRouts.js
  controllers/review.js
  controllers/users.js
  index.js
  middleware/auth.js
  models/fragrance.js
  models/order.js
  models/review.js
  models/user.js
  public/css/addUser.css
  public/css/admin.css
  public/css/editUser.css
  public/css/navBar.css
  public/img/defaultProfilePic.png
  public/js/admin.js
  routes/allroutes.js
  routes/fragrance.js
  routes/frontend.js
  routes/order.js
  routes/publicRoutes.js
  routes/review.js
  routes/users.js
  utilities/emailService.js
  views/404.ejs
  views/admin/addUser.ejs
  views/admin/admin.ejs
  views/admin/editUser.ejs
  views/gifting.ejs
  views/partials/navbar.ejs
Labels: Review effort 4/5

#243 fix fragrance-page route
  routes/frontend.js
Labels: Review effort 1/5

#244 Minor css changes
  public/css/fragrances-page.css
  public/css/style.css
Labels: Review effort 1/5

#246 now admin can edit everything about the user and validation added too
  controllers/users.js
  routes/frontend.js
  routes/users.js
  views/admin/editUser.ejs
Labels: Review effort 2/5

#251 Fragrances Page Design✅
  public/css/fragrances-page.css
  public/css/style.css
  public/js/fragrances-page.js
  views/fragrances-page.ejs
  views/index.ejs
Labels: Review effort 3/5

#256 removed unwanted code making code cleaner
  routes/admin.js
Labels: Review effort 1/5

#257 you can now edit the profile picture from the edit section and added …
  controllers/users.js
  public/uploads/1745886061123-blue.jpg
  public/uploads/1745886350653-blue.jpg
  public/uploads/1745886370289-girltest.jpg
  routes/users.js
  views/admin/editUser.ejs
Labels: Review effort 2/5

#261 added front end for the add freagrance and resposive too
  models/fragrance.js
  public/uploads/1745883806268-me.png
  public/uploads/1745886061123-blue.jpg
  public/uploads/1745886350653-blue.jpg
  public/uploads/1745886370289-girltest.jpg
  public/uploads/1746031859958-me.png
  views/admin/addFragrance.ejs
Labels: Review effort 3/5
